name: Linting and Tests
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  check-code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: python -m pip install tox
      - run: tox -e check_codestyle

  #check-types:
    #name: Check types with Mypy
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- uses: actions/setup-python@v2
        #with:
          #python-version: "3.x"
      #- run: python -m pip install tox
      #- run: tox -e check_types

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run the unit tests both against our oldest supported Python version
        # and the newest stable.
        python_version: [ "3.7", "3.x" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - run: python -m pip install tox
      - run: tox -e py

  packaging:
    name: Check Packaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - run: python -m pip install tox
      - run: tox -e packaging
